### PR TITLE
Create TEMPLATE branch for automated syncing

### PR DESCRIPTION
**Pull request by drpatelh**
Initial creation of TEMPLATE branch to enable automated syncing with new tools releases. Woooohoooo.

### CODE REVIEW

**Comment by apeltzer** [comment]
Don't forget to drop it from the nf-core/tools blacklist too :-)

**Comment by drpatelh** [comment]
Oh yeahhh! Changes wont be in `master` though until I have done a bit more work on the pipeline. Will this break the syncing? 

Got the same situation with `atacseq` because I created `TEMPLATE` after the release...

**Comment by drpatelh** [comment]
Removed `chipseq` from blacklist:
https://github.com/nf-core/tools/pull/332

**Comment by drpatelh** [comment]
Merging this because everything is passing 👍

**Pull request merged**
