### PR TITLE
Filtering macs2 files without peaks

### LINKED ISSUE #128: Error when no peaks are found
Hi there! 

This is an exception that you might want to catch: the experiment of the client failed and we don't see much of an enrichment, and hence no peaks are found at all. Your pipeline crashes with "Error executing process > 'PeakQC'" (plot_macs_qc.r, plot_homer_annotatepeaks.r, cat peak_annotation_header.txt macs_annotatePeaks.summary.txt > macs_annotatePeaks.summary_mqc.tsv)

```
  Error in read.table(PeakFiles[idx], sep = "\t", header = FALSE) :
    no lines available in input
  Execution halted
```

Would you be able to fix this so that the pipeline can finish off even if no peaks are found? 

Best wishes
Katrin

### PR DESCRIPTION
**Pull request by JoseEspinosa**
As explained in #128 when macs2 files have any peak inside an exception is raised.

Closes #128 

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Make sure your code lints (`nf-core lint .`).
- [x] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by JoseEspinosa** [comment]
Have drafted this PR by the moment, although the data in issue #128 is no longer available, I guess you also don't have it @drpatelh :roll_eyes: 
If not we may need in slack for it

**Comment by drpatelh** [comment]
Yep, maybe we ask Pablo on Slack. Wonder if we can sub-sample the test data quite heavily to reproduce? 🤔

**Review by drpatelh — APPROVED** [review]
Nice! You found a real dataset to test with?

**Comment by JoseEspinosa** [comment]
I mixed a file from Pablo with our test-dataset but I think it might be safer than someone else give it a try

**Pull request merged**
