### PR TITLE
Update conda packages, process.container style

### LINKED ISSUE #70: plotFingerprint fails with too many bam files
With  experiment of 36 samples, `plotFingerprint` fails. Scaling back plotFingerprint to 3 bam files removed error. Should be more rigorously tested to figure out maximum number of bam files or if one of my bam files was corrupted. Ideally, pipeline would use `macs.config` file to `plotFingerprint` in groups or just each sample against its respective input. 

Example error section:

```
ERROR ~ Error executing process > 'deepTools (2018_051_S5_R1_001.dedup.sorted)'
Caused by:
  Process `deepTools (2018_051_S5_R1_001.dedup.sorted)` terminated with an error exit status (1)
Command executed:
  plotFingerprint \
      -b 2018_051_S5_R1_001.dedup.sorted.bam 2018_054_S7_R1_001.dedup.sorted.bam 2018_046_S1_R1_001.dedup.sorted.bam 2018_037_S1_R1_001.dedup.sorted.bam 2018_042_S9_R1_001.dedup.sorted.bam 2018_043_S6_R1_001.dedup.sorted.bam 2018_040_S4_R1_001.dedup.sorted.bam 2018_038_S2_R1_001.dedup.sorted.bam 2018_053_S8_R1_001.dedup.sorted.bam 2018_048_S9_R1_001.dedup.sorted.bam 2018_044_S7_R1_001.dedup.sorted.bam 2018_039_S3_R1_001.dedup.sorted.bam 2018_052_S6_R1_001.dedup.sorted.bam 2018_045_S8_R1_001.dedup.sorted.bam 2018_050_S4_R1_001.dedup.sorted.bam 2018_041_S5_R1_001.dedup.sorted.bam 2018_047_S2_R1_001.dedup.sorted.bam 2018_049_S3_R1_001.dedup.sorted.bam 2018_030_S3_R1_001.dedup.sorted.bam 2018_034_S7_R1_001.dedup.sorted.bam 2018_033_S6_R1_001.dedup.sorted.bam 2018_031_S4_R1_001.dedup.sorted.bam 2018_035_S8_R1_001.dedup.sorted.bam 2018_029_S2_R1_001.dedup.sorted.bam 2018_036_S9_R1_001.dedup.sorted.bam 2018_032_S5_R1_001.dedup.sorted.bam 2018_028_S1_R1_001.dedup.sorted.bam 2018_022_S4_R1_001.dedup.sorted.bam 2018_027_S9_R1_001.dedup.sorted.bam 2018_021_S3_R1_001.dedup.sorted.bam 2018_024_S6_R1_001.dedup.sorted.bam 2018_020_S2_R1_001.dedup.sorted.bam 2018_023_S5_R1_001.dedup.sorted.bam 2018_019_S1_R1_001.dedup.sorted.bam 2018_026_S8_R1_001.dedup.sorted.bam 2018_025_S7_R1_001.dedup.sorted.bam \
      --plotFile fingerprints.pdf \
      --outRawCounts fingerprint.txt \
      --extendReads 100 \
      --skipZeros \
      --ignoreDuplicates \
      --numberOfSamples 50000 \
      --binSize 500 \
      --plotFileFormat pdf \
      --plotTitle "Fingerprints"
  
  for bamfile in 2018_051_S5_R1_001.dedup.sorted.bam 2018_054_S7_R1_001.dedup.sorted.bam 2018_046_S1_R1_001.dedup.sorted.bam 2018_037_S1_R1_001.dedup.sorted.bam 2018_042_S9_R1_001.dedup.sorted.bam 2018_043_S6_R1_001.dedup.sorted.bam 2018_040_S4_R1_001.dedup.sorted.bam 2018_038_S2_R1_001.dedup.sorted.bam 2018_053_S8_R1_001.dedup.sorted.bam 2018_048_S9_R1_001.dedup.sorted.bam 2018_044_S7_R1_001.dedup.sorted.bam 2018_039_S3_R1_001.dedup.sorted.bam 2018_052_S6_R1_001.dedup.sorted.bam 2018_045_S8_R1_001.dedup.sorted.bam 2018_050_S4_R1_001.dedup.sorted.bam 2018_041_S5_R1_001.dedup.sorted.bam 2018_047_S2_R1_001.dedup.sorted.bam 2018_049_S3_R1_001.dedup.sorted.bam 2018_030_S3_R1_001.dedup.sorted.bam 2018_034_S7_R1_001.dedup.sorted.bam 2018_033_S6_R1_001.dedup.sorted.bam 2018_031_S4_R1_001.dedup.sorted.bam 2018_035_S8_R1_001.dedup.sorted.bam 2018_029_S2_R1_001.dedup.sorted.bam 2018_036_S9_R1_001.dedup.sorted.bam 2018_032_S5_R1_001.dedup.sorted.bam 2018_028_S1_R1_001.dedup.sorted.bam 2018_022_S4_R1_001.dedup.sorted.bam 2018_027_S9_R1_001.dedup.sorted.bam 2018_021_S3_R1_001.dedup.sorted.bam 2018_024_S6_R1_001.dedup.sorted.bam 2018_020_S2_R1_001.dedup.sorted.bam 2018_023_S5_R1_001.dedup.sorted.bam 2018_019_S1_R1_001.dedup.sorted.bam 2018_026_S8_R1_001.dedup.sorted.bam 2018_025_S7_R1_001.dedup.sorted.bam
  do
      bamCoverage \
        -b $bamfile \
        --extendReads 100 \
        --normalizeUsing RPKM \
        -o ${bamfile}.bw
  done
  
  multiBamSummary \
      bins \
      --binSize 10000 \
      --bamfiles 2018_051_S5_R1_001.dedup.sorted.bam 2018_054_S7_R1_001.dedup.sorted.bam 2018_046_S1_R1_001.dedup.sorted.bam 2018_037_S1_R1_001.dedup.sorted.bam 2018_042_S9_R1_001.dedup.sorted.bam 2018_043_S6_R1_001.dedup.sorted.bam 2018_040_S4_R1_001.dedup.sorted.bam 2018_038_S2_R1_001.dedup.sorted.bam 2018_053_S8_R1_001.dedup.sorted.bam 2018_048_S9_R1_001.dedup.sorted.bam 2018_044_S7_R1_001.dedup.sorted.bam 2018_039_S3_R1_001.dedup.sorted.bam 2018_052_S6_R1_001.dedup.sorted.bam 2018_045_S8_R1_001.dedup.sorted.bam 2018_050_S4_R1_001.dedup.sorted.bam 2018_041_S5_R1_001.dedup.sorted.bam 2018_047_S2_R1_001.dedup.sorted.bam 2018_049_S3_R1_001.dedup.sorted.bam 2018_030_S3_R1_001.dedup.sorted.bam 2018_034_S7_R1_001.dedup.sorted.bam 2018_033_S6_R1_001.dedup.sorted.bam 2018_031_S4_R1_001.dedup.sorted.bam 2018_035_S8_R1_001.dedup.sorted.bam 2018_029_S2_R1_001.dedup.sorted.bam 2018_036_S9_R1_001.dedup.sorted.bam 2018_032_S5_R1_001.dedup.sorted.bam 2018_028_S1_R1_001.dedup.sorted.bam 2018_022_S4_R1_001.dedup.sorted.bam 2018_027_S9_R1_001.dedup.sorted.bam 2018_021_S3_R1_001.dedup.sorted.bam 2018_024_S6_R1_001.dedup.sorted.bam 2018_020_S2_R1_001.dedup.sorted.bam 2018_023_S5_R1_001.dedup.sorted.bam 2018_019_S1_R1_001.dedup.sorted.bam 2018_026_S8_R1_001.dedup.sorted.bam 2018_025_S7_R1_001.dedup.sorted.bam \
      -out multiBamSummary.npz \
      --extendReads 100 \
      --ignoreDuplicates \
      --centerReads
  
  plotCorrelation \
      -in multiBamSummary.npz \
      -o scatterplot_PearsonCorr_multiBamSummary.png \
      --outFileCorMatrix scatterplot_PearsonCorr_multiBamSummary.txt \
      --corMethod pearson \
      --skipZeros \
      --removeOutliers \
      --plotTitle "Pearson Correlation of Read Counts" \
      --whatToPlot scatterplot
  
  plotCorrelation \
      -in multiBamSummary.npz \
      -o heatmap_SpearmanCorr_multiBamSummary.png \
      --outFileCorMatrix heatmap_SpearmanCorr_multiBamSummary.txt \
      --corMethod spearman \
      --skipZeros \
      --plotTitle "Spearman Correlation of Read Counts" \
      --whatToPlot heatmap \
      --colorMap RdYlBu \
      --plotNumbers
  
  plotPCA \
      -in multiBamSummary.npz \
      -o pcaplot_multiBamSummary.png \
      --plotTitle "Principal Component Analysis Plot" \
      --outFileNameData pcaplot_multiBamSummary.txt
Command exit status:
  1
Command output:
  (empty)
Command error:
  Traceback (most recent call last):
    File "/usr/local/apps/deeptools/3.1.3/bin/plotFingerprint", line 12, in <module>
      main(args)
    File "/usr/local/Anaconda/envs_app/deeptools/3.1.3/lib/python3.6/site-packages/deeptools/plotFingerprint.py", line 421, in main
      plt.plot(x, count, label=args.labels[i], linestyle=pyplot_line_styles[j])
  IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by ewels**
Update conda packages. Fixes #70

Update style to match latest linting and template changes.

Tests will fail until new nf-core tools package is release on PyPI.

### CODE REVIEW

**Comment by drpatelh** [comment]
Ideally, `plotFingerprint` is run on the IP and input bams that are used in the `macs` process as opposed to all of them. This will take some rejigging of the code though...
https://github.com/nf-core/chipseq/blob/b4b75ae46c2a5f814992df2dab26f0ea5245e318/main.nf#L871-L878

Can remove `Singularity` file now too right?

`docs` will need to be updated in line with these changes.

**Comment by apeltzer** [comment]
Yes you can remove it now 👍

**Comment by ewels** [comment]
Agreed, but can we do those changes in a different PR? I think that they're kind of separate to the changes here.. correct me if I'm wrong.

**Comment by ewels** [comment]
(we have tonnes of stuff to update in this pipeline to get it in line with the template... Singularity file and others are a drop in the ocean I suspect)

**Comment by drpatelh** [comment]
Yeah, cool to do in another PR. The read filtering and other processes need to be jigged too. I can take care of all that when I free up a little.

I'm quietly hoping the new NF modularisation will help with the processes themselves. Agree that the template will need to be updated extensively too. Patching is fine for now.

Maybe add some of the more pertinent updates you have made to the template and configs recently?

**Comment by pditommaso** [comment]
tip: 

```groovy
ctrl = ctrl_sample_id ? "-c ${ctrl_sample_id}.sorted.bam" : ''
```

**Comment by ewels** [comment]
@drpatelh - Made a new issue #71 for the plotFingerPrint point. The `Singularity` file thing is basically https://github.com/nf-core/chipseq/issues/54

Aside from these two points, is everyone happy with this PR? Can it be merged?

**Comment by drpatelh** [comment]
Cool. Yes fine with me.

**Pull request merged**
