### PR TITLE
Get the tests to pass

### LINKED ISSUE #47: Update core pipeline code
The pipeline has fallen behind some of the more recent updates to the nf-core template. Apply updates until the linting tests are passing again.

### PR DESCRIPTION
**Pull request by ewels**
Fixes #47

### CODE REVIEW

**Comment by chuan-wang** [comment]
In the file `uppmax-modules.config`, the pipeline did not run with `withName:`. It worked when I switched back to `$`. (tests were done under nextflow 0.31.1 on Rackham).

**Comment by ewels** [comment]
I feel that it must be something else... We have made the same change to all other pipelines. What was the error that you got?

**Comment by ewels** [comment]
Core template structure is broken, so my changes here break pipeline execution. Let's hold this until we know more over at https://github.com/nextflow-io/nextflow/issues/840

**Comment by ewels** [comment]
Hmm, tests seem to be failing due to an [unrelated error](https://travis-ci.org/nf-core/chipseq/jobs/417261273#L1089-L1104) in deeptools:

```python
  Traceback (most recent call last):
    File "/opt/conda/envs/nfcore-chipseq-1.0dev/bin/plotPCA", line 11, in <module>
      main(args)
    File "/opt/conda/envs/nfcore-chipseq-1.0dev/lib/python2.7/site-packages/deeptools/plotPCA.py", line 176, in main
      cols=args.colors)
    File "/opt/conda/envs/nfcore-chipseq-1.0dev/lib/python2.7/site-packages/deeptools/correlation.py", line 688, in plot_pca
      plt.tight_layout()
    File "/opt/conda/envs/nfcore-chipseq-1.0dev/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1366, in tight_layout
      fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
    File "/opt/conda/envs/nfcore-chipseq-1.0dev/lib/python2.7/site-packages/matplotlib/figure.py", line 2276, in tight_layout
      self.subplots_adjust(**kwargs)
    File "/opt/conda/envs/nfcore-chipseq-1.0dev/lib/python2.7/site-packages/matplotlib/figure.py", line 2088, in subplots_adjust
      self.subplotpars.update(*args, **kwargs)
    File "/opt/conda/envs/nfcore-chipseq-1.0dev/lib/python2.7/site-packages/matplotlib/figure.py", line 241, in update
      raise ValueError('left cannot be >= right')
  ValueError: left cannot be >= right
```

@chuan-wang or @apeltzer - have you seen this before?

**Comment by ewels** [comment]
Hi @dpryan79 - sorry to ping you, but have you seen this error anywhere else with DeepTools? Any idea how we can resolve it?

Cheers,

Phil

**Comment by dpryan79** [comment]
What version of deepTools are you using in nf-core? @chuan-wang nailed the typical cause, which is a really long sample name. I increased the default width of the output plot in version 3.1.1 due to this (see https://github.com/deeptools/deepTools/issues/738), but perhaps either it needs to be widened further in your case (with `--plotWidth`) or the sample names used in `multiSomethingSummary` need to be set (either with `--labels` or just using `--smartLabels`).

**Comment by ewels** [comment]
Thanks! This is version 3.1.1. As we don't have control of what the sample names will be, I guess we can just supply a truncated version of the sample names... Though maybe this is what `--smartLabels` does? I'll try adding that now..

**Comment by dpryan79** [comment]
By default, labels are the file name and path given to a tool. What `--smartLabels` does is strip off the path and file extension, since that's typically then the sample name people actually care about (or pretty close).

**Comment by ewels** [comment]
Yup, makes sense :+1:

Looks like my quick and dirty attempt with this as I left the office fails - this option isn’t available with `plotPCA` I guess..?

**Comment by dpryan79** [comment]
`--smartLabels` should be used with `multiBamSummary` rather than `plotPCA`. In this case I don't think it will help, you're better off just increasing the width to something like 20.

**Comment by dpryan79** [comment]
Looks like the width change did the trick :)

**Comment by ewels** [comment]
Yes! I'm now just dropping it down a little as it was kind of ridiculous 😅 I'm also looking into removing the `.dedup.sorted` suffix from the filenames as that adds to the sample name length unnecessarily..

**Comment by ewels** [comment]
Latest minor changes working locally, so merging 🎉

**Pull request merged**
