### PR TITLE
Improving function speed

### PR DESCRIPTION
**Pull request by tiagochst**
The post_peak_calling script was a big bottleneck in my runs.
One of the reasons was the loop was quite slow, I improved a little bit the code (summarized in this report http://rpubs.com/tiagochst/post_peak_calling_improvement).

### CODE REVIEW

**Comment by tiagochst** [comment]
Sure I can change the white spaces. I believe my editor is using 2 white spaces as indentation.

I'll add the dependencies to environment file, I thought they were not there since there were some install codes in the code.

**Comment by ewels** [comment]
Thanks! 👍 

> I thought they were not there since there were some install codes in the code.

Yes, this is older boiler-plate code which I left in, mostly in case people are trying to run this with their own installations instead of using the containers provided.

Many people run these pipelines offline, so the containers need to have all software requirements already.

**Comment by tiagochst** [comment]
Parallel comes with R, so I added only r-doparallel.

**Comment by tiagochst** [comment]
Btw, If you don't mind I would prefer to improve the code style.

**Comment by ewels** [comment]
Brilliant, thanks for this! 👍

**Pull request merged**
