### PR TITLE
Update docs and images

### PR DESCRIPTION
**Pull request by drpatelh**
* Update docs in `usage.md` and `output.md`
* More extensive description of `--design` in `usage.md`
* Regenerate and replace images in docs as relevant to ChIP-seq data
* Change parameter names from boolean type to value type for consistency e.g. `fingerprintBins` > `fingerprint_bins`

### CODE REVIEW

**Comment by ewels** [comment]
What do you think about embedding the images in the docs instead of just linking to them? I don't like that you have to click through to each plot to see it. As a user I'd prefer to scroll down the docs to find the plot that looks like the one I'm trying to interpret... Or just for faster reading as someone interested in what the pipeline produces.

**Comment by drpatelh** [comment]
Yes, I agree. I did try that initially. However, I settled for this due to differences in the size of the images, and because it made it more difficult to follow the section headings and text. Willing to give it another shot though to see how it looks! Just needed some friendly criticism :+1: 

Im trying to get this ready for a release in the next week or so. Almost there. Are you ok with the current code on `master` being wiped?

**Comment by ewels** [comment]
Go for it!

**Comment by drpatelh** [comment]
Thanks! Can you have a look at the docs now?
https://github.com/drpatelh/chipseq/blob/master/docs/output.md

**Comment by ewels** [comment]
Brilliant 🎉

**Pull request merged**
